import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import {
    ClerkProvider,
    SignInButton,
    SignUpButton,
    SignedIn,
    SignedOut,
    UserButton,
} from '@clerk/nextjs'
import {Toaster} from "~/components/ui/sonner"

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
    return (
        <div className="flex justify-between items-center w-full border-b font-semibold text-gray-900 p-4">
            <div className="">Galley</div>
            <div>
                <SignedOut>
                    <SignInButton />
                    <SignUpButton />
                </SignedOut>
                <SignedIn>
                    <div>hello???</div>
                    <UserButton />
                </SignedIn>
            </div>

        </div>
    )
}

export default function RootLayout({
  children,
  modal
}: Readonly<{ children: React.ReactNode,
    modal: React.ReactNode}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable} flex-col gap-8`}>
        <body>
          <TopNav />
          {children}
          {modal}
          <div id={"modal-root"}></div>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
