import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
    return (
        <div className="flex justify-between items-center w-full border-b font-semibold text-gray-900 p-4">
            <div className="">Galley</div>
            <div className="">Login In</div>
        </div>
    )
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable} flex-col gap-8`}>

      <body>
      <TopNav />
      {children}</body>
    </html>
  );
}
